version: "3.9"

services:
  db:
    image: postgres:16
    container_name: music_catalog_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_pass
      POSTGRES_DB: music_catalog
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: